# Generated by Django 3.2.17 on 2023-04-04 17:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('residentialAddress', models.CharField(max_length=100)),
                ('birthday', models.CharField(max_length=16)),
                ('socialSecurity', models.CharField(max_length=20)),
                ('securityAnswer1', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailAddress', models.EmailField(max_length=254)),
                ('sentTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardName', models.CharField(max_length=64)),
                ('firstNameBill', models.CharField(max_length=64)),
                ('lastNameBill', models.CharField(max_length=64)),
                ('inputAddress', models.CharField(max_length=64)),
                ('inputCity', models.CharField(max_length=64)),
                ('inputState', models.CharField(max_length=64)),
                ('inputZip', models.CharField(max_length=64)),
                ('paymentMethod', models.CharField(max_length=64)),
                ('cc_name', models.CharField(max_length=64)),
                ('cc_number', models.CharField(max_length=64)),
                ('cc_expiration', models.CharField(max_length=64)),
                ('cc_cvv', models.CharField(max_length=64)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourChoice', models.CharField(max_length=64)),
                ('depart_date', models.DateField(default=datetime.date(2023, 6, 7))),
                ('numTickets', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('failed', 'failed'), ('processed', 'processed'), ('reviewing', 'reviewing'), ('approved', 'approved'), ('redeemed', 'redeemed'), ('completed', 'completed')], default='pending', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odyssey.payment')),
            ],
        ),
        migrations.CreateModel(
            name='LoginPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pingType', models.CharField(default='Admin Login', max_length=16, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HelpTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('question', models.TextField()),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
