# Generated by Django 4.1.6 on 2023-02-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourChoice', models.CharField(max_length=64)),
                ('firstName', models.CharField(max_length=64)),
                ('lastName', models.CharField(max_length=64)),
                ('birthday', models.CharField(max_length=16)),
                ('firstNameBill', models.CharField(max_length=64)),
                ('lastNameBill', models.CharField(max_length=64)),
                ('inputAddress', models.CharField(max_length=64)),
                ('inputAddress2', models.CharField(max_length=64)),
                ('inputCity', models.CharField(max_length=64)),
                ('inputState', models.CharField(max_length=64)),
                ('inputZip', models.CharField(max_length=64)),
                ('paymentMethod', models.CharField(max_length=64)),
                ('cc_name', models.CharField(max_length=64)),
                ('cc_number', models.CharField(max_length=64)),
                ('cc_expiration', models.CharField(max_length=64)),
                ('cc_cvv', models.CharField(max_length=64)),
            ],
        ),
    ]
