# Generated by Django 4.1.6 on 2023-02-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odyssey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='inputAddress2',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
