# Generated by Django 3.2.17 on 2023-03-01 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('odyssey', '0003_create_super_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('residentialAddress', models.CharField(max_length=100)),
                ('birthday', models.CharField(max_length=16)),
                ('socialSecurity', models.CharField(max_length=20)),
                ('securityAnswer1', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourChoice', models.CharField(max_length=64)),
                ('passengerFirstName', models.CharField(max_length=64)),
                ('passengerLastName', models.CharField(max_length=64)),
                ('birthday', models.CharField(max_length=16)),
                ('socialSecurity', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('failed', 'failed'), ('processed', 'processed'), ('reviewing', 'reviewing'), ('approved', 'approved'), ('completed', 'completed')], default='pending', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odyssey.account')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstNameBill', models.CharField(max_length=64)),
                ('lastNameBill', models.CharField(max_length=64)),
                ('inputAddress', models.CharField(max_length=64)),
                ('inputAddress2', models.CharField(max_length=64, null=True)),
                ('inputCity', models.CharField(max_length=64)),
                ('inputState', models.CharField(max_length=64)),
                ('inputZip', models.CharField(max_length=64)),
                ('paymentMethod', models.CharField(max_length=64)),
                ('cc_name', models.CharField(max_length=64)),
                ('cc_number', models.CharField(max_length=64)),
                ('cc_expiration', models.CharField(max_length=64)),
                ('cc_cvv', models.CharField(max_length=64)),
                ('aaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odyssey.account')),
            ],
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odyssey.payment'),
        ),
    ]
