# Generated by Django 3.2.17 on 2023-03-01 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odyssey', '0004_auto_20230301_0504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='aaccount',
            new_name='account',
        ),
    ]
