# Generated by Django 3.2.17 on 2023-03-15 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('odyssey', '0006_auto_20230301_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourChoice', models.CharField(max_length=64)),
                ('departDate', models.CharField(max_length=64)),
                ('ticketCount', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('failed', 'failed'), ('processed', 'processed'), ('reviewing', 'reviewing'), ('approved', 'approved'), ('redeemed', 'redeemed'), ('completed', 'completed')], default='pending', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odyssey.payment')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
