# Generated by Django 3.2.17 on 2023-03-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odyssey', '0007_auto_20230315_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cardName',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
