# Generated by Django 3.2.17 on 2023-03-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odyssey', '0008_payment_cardname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='inputAddress2',
        ),
    ]
