# Generated by Django 3.2.17 on 2023-03-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odyssey', '0010_loginping'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginping',
            name='pingType',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
