# Generated by Django 3.2.17 on 2023-03-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odyssey', '0011_loginping_pingtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginping',
            name='pingType',
            field=models.CharField(default='Admin Login', max_length=16, null=True),
        ),
    ]
